


TIME_FEATURES = ['DayOfWeek', 'Month', 'Hourly']
CONTINUOUS_FEATURES = ['Z_score', 'RSI', 'boll', 'ULTOSC', 'pct_change', 'zsVol',
       'PR_MA_Ratio_short', 'MA_Ratio_short', 'MA_Ratio', 'PR_MA_Ratio',
       'CDL2CROWS', 'CDL3BLACKCROWS','CDL3WHITESOLDIERS', 'CDLABANDONEDBABY',
       'CDLBELTHOLD', 'CDLCOUNTERATTACK', 'CDLDARKCLOUDCOVER', 'CDLDRAGONFLYDOJI',
       'CDLENGULFING', 'CDLEVENINGDOJISTAR', 'CDLEVENINGSTAR',
       'CDLGRAVESTONEDOJI', 'CDLHANGINGMAN', 'CDLHARAMICROSS',
       'CDLINVERTEDHAMMER', 'CDLMARUBOZU', 'CDLMORNINGDOJISTAR',
       'CDLMORNINGSTAR', 'CDLPIERCING', 'CDLRISEFALL3METHODS',
       'CDLSHOOTINGSTAR', 'CDLSPINNINGTOP', 'CDLUPSIDEGAP2CROWS']

B_WINDOW = 5
F_WINDOW = 2

ALPHA_PTH = 0.8
BETA_PTH = 0.97

PCT_PERIOD = 1

